### ISSUE TITLE
Contriubted-modules Typo

### ISSUE THREAD

**Issue by devekko** [aegir-project/documentation#13]
I cant find this Contriubted-modules in the source

but, its in the HTML title

**Comment by helmo** [comment]
It was in mkdocs.yml, fixed in 51ccc081f1f906c36a6c8150fbd781b6c14a3042

**Comment by devekko** [comment]
weird 
cant find it on my fork
https://github.com/devekko/documentation/search?utf8=%E2%9C%93&q=Contriubted-modules

anyways, glad its fixed

**Comment by helmo** [comment]
On 12-09-15 05:54, Nicholas Roberts wrote:

> weird
> cant find it on my fork
> https://github.com/devekko/documentation/search?utf8=%E2%9C%93&q=Contriubted-modules
> 
> anyways, glad its fixed

How nice of Github :(, after you click on  "< > Code" you get an error.

"Sorry, forked repositories are not currently searchable."

So gh was just searching issues for you.

## 

Met vriendelijke groet / Regards,

Herman van Rink
Initfour websolutions

**Comment by niccolox** [comment]
No wonder gitlab.com is doing so well
I much prefer it
