### ISSUE TITLE
Readthedocs search bar never yields any results

### ISSUE THREAD

**Issue by colans** [aegir-project/documentation#21]
For example, this is a search for the word "site":

https://readthedocs.org/search/?q=site&check_keywords=yes&area=default&project=aegir&version=3.x&type=file

**Comment by joestewart** [comment]
Long standing upstream issue isn't it?  https://github.com/rtfd/readthedocs.org/issues/1487

**Comment by ergonlogic** [comment]
Looks like there's a separate `mkdocs json` command that needs to be run to output the JSON format required for RTFD search. I'll see if I can get it to work.

**Comment by ergonlogic** [comment]
Looks like the `mkdocs json` command is run by RTD when building our docs, as seen on the project page. In fact, using the search box within the RTD block in the lower left results in working search: https://readthedocs.org/projects/aegir/search/?q=site. Also, the search.html page in our docs works too: http://docs.aegirproject.org/en/3.x/search.html.

**Comment by ergonlogic** [comment]
Fixed in 3a44eec1

**Comment by colans** [comment]
Works, thanks! It's funny that it flashes on a "Sorry, page not found." page for a moment before showing the results page, but I'm happy.

**Comment by ergonlogic** [comment]
Yeah, that's the default on the search results page, before it's replaced by the search results: http://docs.aegirproject.org/en/3.x/search.html. We could override that template too, and put in a "Searching..." string, I suppose.
