### ISSUE TITLE
Fix instructions for upgrading Drupal core

### ISSUE THREAD

**Issue by colans** [aegir-project/documentation#22]
At http://docs.aegirproject.org/en/3.x/install/upgrade/#the-hostmaster-migrate-command, I added instructions for upgrading Drupal core to a new release if one doesn't want to wait for a new Aegir release (say to avoid security vulnerabilities).

However, it's a dangerous in-place recipe.  Now that the changes from https://www.drupal.org/node/2698027 are in, we should update these instructions to use hostmaster-migrate instead.  It'll now grab the latest stable Drupal core.

It needs more testing though as only @helmo has confirmed that this works.

**Comment by helmo** [comment]
We can for now add another command to run ... updb (although it's not required for 7.52)

``` md
1. Run database updates
    * `drush @hostmaster updatedb`
```

**Comment by helmo** [comment]
Added in f6ab42369b5c56510acf63fb0a46e712aef171a4

**Comment by colans** [comment]
Shouldn't we switch these instructions to the safer `hostmaster-migrate` plan, as I mentioned in the description?

**Comment by helmo** [comment]
Feel free to ... but after almost 2 years I got the feeling that this would never get priority.

**Comment by colans** [comment]
Moved to https://gitlab.com/aegir/documentation/issues/3.
