### ISSUE TITLE
How can I browse aegir with physical IP  from a non- localhost  ?

### ISSUE THREAD

**Issue by EthanAIPro** [aegir-project/documentation#44]
I have intalled aegir sucess,and can browse aegir on localhost. but i can't browse aegir from other computer. 
1,My network environment is Intranet 
2, my /etc/hosts configuration is follow:
(aegir is hostname,10.100.96.242 is  physical IP,aegir.ahut.edu is Is not a real domain name  )
j~$ cat /etc/hosts 
127.0.0.1       aegir.ahut.edu aegir
10.100.96.242   aegir.ahut.edu aegir
  Please help me, you are all I have.

**Comment by mlutfy** [comment]
On your other computer, you probably want only:

```
10.100.96.242 aegir.ahut.edu aegir
```

(not the 127.0.0.1 entry)

**Comment by EthanAIPro** [comment]
Thank you very much!@mlutfy   I doubt whether I understand what you mean .
I have add the follow code `10.100.96.242 aegir.ahut.edu aegir` on my another computer.
but , I still can't browse aegir from  another computer, I can browse aegir with aegir.ahut.edu or 10.100.96.242 from localhost computer(10.100.96.242 is physical IP)
I guess Is it what I should configure on the apache.conf file? 

I only know a little about the configuration of apahce.

The follow code is my VirtualHost VirtualHost configuration 

```
<VirtualHost *:80>


  DocumentRoot /var/aegir/hostmaster-7.x-3.11.2
  ServerName aegir.ahut.edu
#  ServerName 10.100.96.242
  SetEnv db_type  mysql
  SetEnv db_name  aegirahutedu
  SetEnv db_user  aegirahutedu
  SetEnv db_passwd  xxxxx
  SetEnv db_host  localhost
  SetEnv db_port  3306

  ServerAlias 10.100.96.242

<IfModule mod_rewrite.c>
  RewriteEngine on
 # Redirect all aliases to the main http url.
 RewriteCond %{HTTP_HOST} !^aegir.ahut.edu$ [NC]
 RewriteRule ^/*(.*)$ http://aegir.ahut.edu/$1 [NE,L,R=301]
  RewriteRule ^/files/(.*)$ /sites/aegir.ahut.edu/files/$1 [L]
  RewriteCond /var/aegir/hostmaster-7.x-3.11.2/sites/aegir.ahut.edu/files/robots.txt -f
  RewriteRule ^/robots.txt /sites/aegir.ahut.edu/files/robots.txt [L]
</IfModule>

# Extra configuration from modules:

    # Error handler for Drupal > 4.6.7
    <Directory ~ "sites/.*/files">
      <Files *>
        SetHandler This_is_a_Drupal_security_line_do_not_remove
      </Files>
      Options None
      Options +FollowSymLinks

      # If we know how to do it safely, disable the PHP engine entirely.
      <IfModule mod_php5.c>
        php_flag engine off
      </IfModule>
    </Directory>

    # Prevent direct reading of files in the private dir.
    # This is for Drupal7 compatibility, which would normally drop
    # a .htaccess in those directories, but we explicitly ignore those
    <Directory "/var/aegir/hostmaster-7.x-3.11.2/sites/aegir.ahut.edu/private/" >
      <Files *>
        SetHandler This_is_a_Drupal_security_line_do_not_remove
      </Files>
      Deny from all
      Options None
      Options +FollowSymLinks

      # If we know how to do it safely, disable the PHP engine entirely.
      <IfModule mod_php5.c>
        php_flag engine off
      </IfModule>
    </Directory>

```

**Comment by mlutfy** [comment]
Seems OK to me. From the other computer, what does the browser display? (i.e. error message? default vhost? does it fail to connect?)

**Comment by jileieli** [comment]
On my non local computer, when I entered the IP address in the browser address bar, my computer could resolve the IP address to aegir.ahut.edu, but I couldn't get the Aegir details.

**Comment by EthanAIPro** [comment]
Thank you very much @mlutfy  .On my other computer, set my hosts file with follow is a good solution to my question:
`10.100.96.242 aegir.ahut.edu aegir`

I didn't have any effect after setting up last night. It's already possible to try again today. Maybe I haven't made it up yet before I browse.

Thank you for your prompt answer. It saved me a lot of time.

**Comment by helmo** [comment]
sounds resolved...
