### ISSUE TITLE
Installation instructions for CentOS 7.x

### ISSUE THREAD

**Issue by AlexShapka** [aegir-project/documentation#50]
Could not find any installation guide for Aegir on CentOS except this outdated on https://groups.drupal.org/node/29844. Even-though the http://docs.aegirproject.org/en/3.x/install states:

> These instructions provide example commands for a Debian-like distribution, but should be fairly easy to adapt to other environments. 

it would be really nice to have the detailed steps for installing Aegir on CentOS 7.x.

Also I wonder if the project is alive at all as the previous issue here (https://github.com/aegir-project/documentation/issues/24) was created back in 2016. Is it still supported?

**Comment by helmo** [comment]
Thanks for your interest, yes it is active ... most activity is however on Drupal.org
The most central is https://www.drupal.org/project/hostmaster

but D.o also  offers a combined search of most of our modules via this long link:

https://www.drupal.org/project/issues?projects=provision%2C+hosting%2C+eldir%2C+Hostmaster+%28Aegir%29%2C+Aegir+Hosting+Git%2C+Aegir+Hosting+tasks+extra%2C+Aegir+Hosting+Logs%2C+Hosting+Site+Backup+Manager%2C+Aegir+Hosting+Remote+Import%2C+Aegir+HTTPS

I'm not aware of anyone in the core team using CentOS which makes it hard to maintain... but I'd welcome anyone who wanted to step in and take a stab at this.

**Comment by colans** [comment]
Moved to https://gitlab.com/aegir/documentation/issues/2 as we're no longer using GitHub.
