### ISSUE TITLE
Navigation menu is broken/unusable

### ISSUE THREAD

**Issue by colans** [aegir-project/documentation#51]
![screenshot_2018-10-22 platforms - aegir hosting system](https://user-images.githubusercontent.com/1258265/47315258-0ebfb400-d612-11e8-8a9e-7594343a17ad.png)

Tested on both Chromium and Firefox.

**Comment by helmo** [comment]
@jonpugh suggested Gitbook. How much effort would it be to git the docs up there properly?

I've been wanting to try the GitLab wiki for a while now so I've also pushed a branch there and with only a few adjustments it's now showing the basics on https://gitlab.com/aegir/documentation/wikis/

The menu is not perfect there either :( ... I added a custom _sidebar.md for it. But it's lacking scrollbars (or a way to collapse items)

**Comment by colans** [comment]
@ergonlogic How much work do you think it would be do convert to Hugo, if you think it'd be worthwhile?

@helmo It looks okay on the Gitlab wiki.  I think we'd only need to fix the *[TOC]* display which we can find with a regex search.  Maybe this is all we need to do for now, and see how it works.

**Comment by helmo** [comment]
Strange idea ... I just removed all the custom theming from mkdocs.conf ... see 8b3c77ef847455d3aa7c00d6d1c98cbbf6a3e728

Now the tree is no longer collapsed ... but usable :)

**Comment by colans** [comment]
Looks good to me.  Folks can open a new issue if they're like to bring that back (working).
