### ISSUE TITLE
RTD build failure

### ISSUE THREAD

**Issue by helmo** [aegir-project/documentation#54]
The docs were not updating.

I'm not sure who set it up (@ergonlogic ? ) ... but as I was unable to see build logs I moved it to [GitLab CI yesterday](https://gitlab.com/aegir/documentation/pages).
However read the docs seems to add a /en prefix in the url path, which the new location is missing.
My first attempt at a redirect to counter this failed in 47f2168b58ec4494bb857538b5c0dced369e5d16

I've created a new rtd account to see what happens, here's the [buildlog](https://readthedocs.org/api/v2/build/8446820.txt)
`ERROR   -  Config value: 'pages'. Error: Invalid pages config.`

Did the config format change between versions?

@jonpugh ideas?

**Comment by colans** [comment]
As we're now running this exclusively using GitLab, closing.
